#!/bin/dash

set -x

echo "Starting builder"

cd /go/src
go get -v ./...

while true; do
  if [ -x /go/build/build ]; then
    /go/build/build
  else
    echo No build file
  fi
  inotifywait -qr -e modify,create,delete,move .
done
